<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.apzda.hajimi</groupId>
        <artifactId>hajimi-ucenter</artifactId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>hajimi-ucenter-client</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.apzda.hajimi</groupId>
            <artifactId>hajimi-ucenter-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.apzda.cloud</groupId>
            <artifactId>kalami-spring-boot-security</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- 通过openfeign提供服务时本工程只能像下边这样引入依赖 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-openfeign-core</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- 其它第三方类库 -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
